import type { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: "1",
    name: "Colar Delicado Dourado",
    price: 89.9,
    originalPrice: 129.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Colar+Dourado",
      "/placeholder.svg?height=400&width=400&text=Colar+Dourado+2",
      "/placeholder.svg?height=400&width=400&text=Colar+Dourado+3",
    ],
    category: "Colares",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.8,
    reviews: 127,
    description:
      "Colar delicado com acabamento dourado, perfeito para o dia a dia. Feito em aço inoxidável com banho de ouro 18k, garantindo durabilidade e brilho duradouro.",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Brincos Argola Média",
    price: 45.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Brincos+Argola",
      "/placeholder.svg?height=400&width=400&text=Brincos+Argola+2",
    ],
    category: "Brincos",
    material: "Aço Inoxidável",
    color: "Prata",
    rating: 4.6,
    reviews: 89,
    description: "Brincos argola de tamanho médio, versáteis e elegantes. Ideais para compor looks casuais e formais.",
    inStock: true,
    featured: false,
  },
  {
    id: "3",
    name: "Anel Solitário Cristal",
    price: 67.9,
    originalPrice: 89.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Anel+Solitario",
      "/placeholder.svg?height=400&width=400&text=Anel+Solitario+2",
      "/placeholder.svg?height=400&width=400&text=Anel+Solitario+3",
    ],
    category: "Anéis",
    material: "Aço Inoxidável com Zircônia",
    color: "Prata",
    rating: 4.9,
    reviews: 203,
    description:
      "Anel solitário com cristal de zircônia cúbica, elegante e sofisticado. Perfeito para ocasiões especiais.",
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    name: "Pulseira Corrente Dourada",
    price: 78.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Pulseira+Corrente",
      "/placeholder.svg?height=400&width=400&text=Pulseira+Corrente+2",
    ],
    category: "Pulseiras",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.7,
    reviews: 156,
    description:
      "Pulseira em corrente dourada, resistente e com design moderno. Ajustável para diferentes tamanhos de pulso.",
    inStock: true,
    featured: false,
  },
  {
    id: "5",
    name: "Conjunto Colar e Brincos",
    price: 134.9,
    originalPrice: 189.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Conjunto+Completo",
      "/placeholder.svg?height=400&width=400&text=Conjunto+Completo+2",
      "/placeholder.svg?height=400&width=400&text=Conjunto+Completo+3",
    ],
    category: "Conjuntos",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.8,
    reviews: 94,
    description:
      "Conjunto harmonioso com colar e brincos combinando. Ideal para presentes ou para criar um look coordenado.",
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    name: "Brincos Gota Pérola",
    price: 52.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Brincos+Perola",
      "/placeholder.svg?height=400&width=400&text=Brincos+Perola+2",
    ],
    category: "Brincos",
    material: "Aço Inoxidável com Pérola Sintética",
    color: "Prata",
    rating: 4.5,
    reviews: 67,
    description:
      "Brincos em formato de gota com pérola sintética, elegantes e femininos. Perfeitos para ocasiões especiais.",
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    name: "Anel Triplo Minimalista",
    price: 43.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Anel+Triplo",
      "/placeholder.svg?height=400&width=400&text=Anel+Triplo+2",
    ],
    category: "Anéis",
    material: "Aço Inoxidável",
    color: "Prata",
    rating: 4.4,
    reviews: 112,
    description:
      "Anel com design triplo minimalista, moderno e versátil. Pode ser usado sozinho ou combinado com outros anéis.",
    inStock: true,
    featured: false,
  },
  {
    id: "8",
    name: "Colar Choker Corrente",
    price: 65.9,
    originalPrice: 89.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Choker+Corrente",
      "/placeholder.svg?height=400&width=400&text=Choker+Corrente+2",
    ],
    category: "Colares",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.6,
    reviews: 78,
    description: "Choker em corrente dourada, tendência e estiloso. Ajustável e perfeito para looks modernos.",
    inStock: true,
    featured: false,
  },
  {
    id: "9",
    name: "Pulseira Charm Coração",
    price: 87.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Pulseira+Charm",
      "/placeholder.svg?height=400&width=400&text=Pulseira+Charm+2",
      "/placeholder.svg?height=400&width=400&text=Pulseira+Charm+3",
    ],
    category: "Pulseiras",
    material: "Aço Inoxidável com Pingente",
    color: "Prata",
    rating: 4.7,
    reviews: 145,
    description: "Pulseira com charm em formato de coração, romântica e delicada. Ideal para presentes especiais.",
    inStock: true,
    featured: true,
  },
  {
    id: "10",
    name: "Brincos Ear Cuff Dourado",
    price: 38.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Ear+Cuff",
      "/placeholder.svg?height=400&width=400&text=Ear+Cuff+2",
    ],
    category: "Brincos",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.3,
    reviews: 56,
    description: "Ear cuff moderno e descolado, não precisa de furo. Tendência atual que adiciona estilo ao visual.",
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    name: "Anel Signet Personalizado",
    price: 95.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Anel+Signet",
      "/placeholder.svg?height=400&width=400&text=Anel+Signet+2",
    ],
    category: "Anéis",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.8,
    reviews: 89,
    description: "Anel signet com possibilidade de personalização, elegante e marcante. Símbolo de sofisticação.",
    inStock: true,
    featured: false,
  },
  {
    id: "12",
    name: "Colar Camadas Múltiplas",
    price: 112.9,
    originalPrice: 149.9,
    images: [
      "/placeholder.svg?height=400&width=400&text=Colar+Camadas",
      "/placeholder.svg?height=400&width=400&text=Colar+Camadas+2",
      "/placeholder.svg?height=400&width=400&text=Colar+Camadas+3",
    ],
    category: "Colares",
    material: "Aço Inoxidável Banhado a Ouro",
    color: "Dourado",
    rating: 4.9,
    reviews: 167,
    description: "Colar com múltiplas camadas em diferentes comprimentos, criando um visual sofisticado e moderno.",
    inStock: true,
    featured: true,
  },
]

export const categories = [
  { id: "colares", name: "Colares", count: 4 },
  { id: "brincos", name: "Brincos", count: 4 },
  { id: "aneis", name: "Anéis", count: 3 },
  { id: "pulseiras", name: "Pulseiras", count: 2 },
  { id: "conjuntos", name: "Conjuntos", count: 1 },
]

export const materials = [
  { id: "aco-inoxidavel", name: "Aço Inoxidável" },
  { id: "banho-ouro", name: "Banhado a Ouro" },
  { id: "zirconia", name: "Com Zircônia" },
  { id: "perola", name: "Com Pérola" },
]

export const colors = [
  { id: "dourado", name: "Dourado" },
  { id: "prata", name: "Prata" },
  { id: "rose", name: "Rose Gold" },
]
